/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// ClusterOverridePolicyListerExpansion allows custom methods to be added to
// ClusterOverridePolicyLister.
type ClusterOverridePolicyListerExpansion interface{}

// OverridePolicyListerExpansion allows custom methods to be added to
// OverridePolicyLister.
type OverridePolicyListerExpansion interface{}

// OverridePolicyNamespaceListerExpansion allows custom methods to be added to
// OverridePolicyNamespaceLister.
type OverridePolicyNamespaceListerExpansion interface{}

// PropagationListerExpansion allows custom methods to be added to
// PropagationLister.
type PropagationListerExpansion interface{}

// PropagationNamespaceListerExpansion allows custom methods to be added to
// PropagationNamespaceLister.
type PropagationNamespaceListerExpansion interface{}
