/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/Gentleelephant/custom-controller/pkg/apis/policy/v1"
	scheme "github.com/Gentleelephant/custom-controller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PropagationsGetter has a method to return a PropagationInterface.
// A group's client should implement this interface.
type PropagationsGetter interface {
	Propagations(namespace string) PropagationInterface
}

// PropagationInterface has methods to work with Propagation resources.
type PropagationInterface interface {
	Create(ctx context.Context, propagation *v1.Propagation, opts metav1.CreateOptions) (*v1.Propagation, error)
	Update(ctx context.Context, propagation *v1.Propagation, opts metav1.UpdateOptions) (*v1.Propagation, error)
	UpdateStatus(ctx context.Context, propagation *v1.Propagation, opts metav1.UpdateOptions) (*v1.Propagation, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Propagation, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.PropagationList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Propagation, err error)
	PropagationExpansion
}

// propagations implements PropagationInterface
type propagations struct {
	client rest.Interface
	ns     string
}

// newPropagations returns a Propagations
func newPropagations(c *PolicyV1Client, namespace string) *propagations {
	return &propagations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the propagation, and returns the corresponding propagation object, and an error if there is any.
func (c *propagations) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Propagation, err error) {
	result = &v1.Propagation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("propagations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Propagations that match those selectors.
func (c *propagations) List(ctx context.Context, opts metav1.ListOptions) (result *v1.PropagationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.PropagationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("propagations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested propagations.
func (c *propagations) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("propagations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a propagation and creates it.  Returns the server's representation of the propagation, and an error, if there is any.
func (c *propagations) Create(ctx context.Context, propagation *v1.Propagation, opts metav1.CreateOptions) (result *v1.Propagation, err error) {
	result = &v1.Propagation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("propagations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(propagation).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a propagation and updates it. Returns the server's representation of the propagation, and an error, if there is any.
func (c *propagations) Update(ctx context.Context, propagation *v1.Propagation, opts metav1.UpdateOptions) (result *v1.Propagation, err error) {
	result = &v1.Propagation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("propagations").
		Name(propagation.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(propagation).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *propagations) UpdateStatus(ctx context.Context, propagation *v1.Propagation, opts metav1.UpdateOptions) (result *v1.Propagation, err error) {
	result = &v1.Propagation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("propagations").
		Name(propagation.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(propagation).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the propagation and deletes it. Returns an error if one occurs.
func (c *propagations) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("propagations").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *propagations) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("propagations").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched propagation.
func (c *propagations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Propagation, err error) {
	result = &v1.Propagation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("propagations").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
