/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/Gentleelephant/custom-controller/pkg/apis/policy/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePropagations implements PropagationInterface
type FakePropagations struct {
	Fake *FakePolicyV1
	ns   string
}

var propagationsResource = v1.SchemeGroupVersion.WithResource("propagations")

var propagationsKind = v1.SchemeGroupVersion.WithKind("Propagation")

// Get takes name of the propagation, and returns the corresponding propagation object, and an error if there is any.
func (c *FakePropagations) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Propagation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(propagationsResource, c.ns, name), &v1.Propagation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Propagation), err
}

// List takes label and field selectors, and returns the list of Propagations that match those selectors.
func (c *FakePropagations) List(ctx context.Context, opts metav1.ListOptions) (result *v1.PropagationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(propagationsResource, propagationsKind, c.ns, opts), &v1.PropagationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.PropagationList{ListMeta: obj.(*v1.PropagationList).ListMeta}
	for _, item := range obj.(*v1.PropagationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested propagations.
func (c *FakePropagations) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(propagationsResource, c.ns, opts))

}

// Create takes the representation of a propagation and creates it.  Returns the server's representation of the propagation, and an error, if there is any.
func (c *FakePropagations) Create(ctx context.Context, propagation *v1.Propagation, opts metav1.CreateOptions) (result *v1.Propagation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(propagationsResource, c.ns, propagation), &v1.Propagation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Propagation), err
}

// Update takes the representation of a propagation and updates it. Returns the server's representation of the propagation, and an error, if there is any.
func (c *FakePropagations) Update(ctx context.Context, propagation *v1.Propagation, opts metav1.UpdateOptions) (result *v1.Propagation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(propagationsResource, c.ns, propagation), &v1.Propagation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Propagation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePropagations) UpdateStatus(ctx context.Context, propagation *v1.Propagation, opts metav1.UpdateOptions) (*v1.Propagation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(propagationsResource, "status", c.ns, propagation), &v1.Propagation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Propagation), err
}

// Delete takes name of the propagation and deletes it. Returns an error if one occurs.
func (c *FakePropagations) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(propagationsResource, c.ns, name, opts), &v1.Propagation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePropagations) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(propagationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.PropagationList{})
	return err
}

// Patch applies the patch and returns the patched propagation.
func (c *FakePropagations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Propagation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(propagationsResource, c.ns, name, pt, data, subresources...), &v1.Propagation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Propagation), err
}
