/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/Gentleelephant/custom-controller/pkg/apis/work/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterResourceBindings implements ClusterResourceBindingInterface
type FakeClusterResourceBindings struct {
	Fake *FakeWorkV1
}

var clusterresourcebindingsResource = v1.SchemeGroupVersion.WithResource("clusterresourcebindings")

var clusterresourcebindingsKind = v1.SchemeGroupVersion.WithKind("ClusterResourceBinding")

// Get takes name of the clusterResourceBinding, and returns the corresponding clusterResourceBinding object, and an error if there is any.
func (c *FakeClusterResourceBindings) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ClusterResourceBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusterresourcebindingsResource, name), &v1.ClusterResourceBinding{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ClusterResourceBinding), err
}

// List takes label and field selectors, and returns the list of ClusterResourceBindings that match those selectors.
func (c *FakeClusterResourceBindings) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ClusterResourceBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusterresourcebindingsResource, clusterresourcebindingsKind, opts), &v1.ClusterResourceBindingList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ClusterResourceBindingList{ListMeta: obj.(*v1.ClusterResourceBindingList).ListMeta}
	for _, item := range obj.(*v1.ClusterResourceBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterResourceBindings.
func (c *FakeClusterResourceBindings) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusterresourcebindingsResource, opts))
}

// Create takes the representation of a clusterResourceBinding and creates it.  Returns the server's representation of the clusterResourceBinding, and an error, if there is any.
func (c *FakeClusterResourceBindings) Create(ctx context.Context, clusterResourceBinding *v1.ClusterResourceBinding, opts metav1.CreateOptions) (result *v1.ClusterResourceBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusterresourcebindingsResource, clusterResourceBinding), &v1.ClusterResourceBinding{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ClusterResourceBinding), err
}

// Update takes the representation of a clusterResourceBinding and updates it. Returns the server's representation of the clusterResourceBinding, and an error, if there is any.
func (c *FakeClusterResourceBindings) Update(ctx context.Context, clusterResourceBinding *v1.ClusterResourceBinding, opts metav1.UpdateOptions) (result *v1.ClusterResourceBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusterresourcebindingsResource, clusterResourceBinding), &v1.ClusterResourceBinding{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ClusterResourceBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterResourceBindings) UpdateStatus(ctx context.Context, clusterResourceBinding *v1.ClusterResourceBinding, opts metav1.UpdateOptions) (*v1.ClusterResourceBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusterresourcebindingsResource, "status", clusterResourceBinding), &v1.ClusterResourceBinding{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ClusterResourceBinding), err
}

// Delete takes name of the clusterResourceBinding and deletes it. Returns an error if one occurs.
func (c *FakeClusterResourceBindings) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(clusterresourcebindingsResource, name, opts), &v1.ClusterResourceBinding{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterResourceBindings) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusterresourcebindingsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ClusterResourceBindingList{})
	return err
}

// Patch applies the patch and returns the patched clusterResourceBinding.
func (c *FakeClusterResourceBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ClusterResourceBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterresourcebindingsResource, name, pt, data, subresources...), &v1.ClusterResourceBinding{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ClusterResourceBinding), err
}
