apiVersion: sync.kubesphere.io/v1
kind: ClusterSyncPolicy
metadata:
  name: clustersync-policy
spec:
  resourceSelectors:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  placement:
    clusterAffinity:
      clusterNames:
        - host
#  overrideRules:
#    - targetCluster:
#        clusterNames:
#          - member1
#      overriders:
#        plaintext:
#        - path: /spec/replicas
#          operator: replace
#          value: 2
