apiVersion: distribution.kubesphere.io/v1
kind: ResourceDistribution
metadata:
  name: my-policy-test
spec:
  resourceSelector:
    apiVersion: apps/v1
    kind: Deployment
#    name: nginx-deployment
    namespace: default
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
  overrideRules:
    - targetCluster:
        clusterNames:
          - member1
      overriders:
        plaintext:
        - path: /spec/replicas
          operator: replace
          value: 2
      ruleName: rule1
    - targetCluster:
        clusterNames:
          - member2
      overriders:
        plaintext:
          - path: /spec/replicas
            operator: replace
            value: 3
      ruleName: rule2