apiVersion: cluster.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    kubesphere.io/description: The description was created by KubeSphere automatically.
      It is recommended that you use the Host Cluster to manage clusters only and
      deploy workloads on Member Clusters.
  finalizers:
  - finalizer.cluster.kubesphere.io
  labels:
    kubesphere.io/managed: "true"
  name: test
spec:
  connection:
    kubeconfig: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VNdmFrTkRRV1ZoWjBGM1NVSkJaMGxDUVVSQlRrSm5hM0ZvYTJsSE9YY3dRa0ZSYzBaQlJFRldUVkpOZDBWUldVUldVVkZFUlhkd2NtUlhTbXdLWTIwMWJHUkhWbnBOUWpSWVJGUkplazFFU1hsT2VrRjVUVlJyZVUxc2IxaEVWRTE2VFVSSmVVNUVRWGxOVkd0NVRXeHZkMFpVUlZSTlFrVkhRVEZWUlFwQmVFMUxZVE5XYVZwWVNuVmFXRkpzWTNwRFEwRlRTWGRFVVZsS1MyOWFTV2gyWTA1QlVVVkNRbEZCUkdkblJWQkJSRU5EUVZGdlEyZG5SVUpCVGpFeENqZE1Wa1l6ZEdSNlMwOXRUelZJTVZWUGJsWlBaemh3U1ROYVYzcFlkVnBEYmtVeVQzVk1XV0pNTDBWbVFpczBXbmw1TlVsdGFsaE9VRFIwWVVObFVEVUtPR3RDWlRCbWRUUlZUa2RYTjFaNmFUbE9lRVZOUVZoVmNsaEdOMDFwYzBVek1YWXpWV3hwUzJKS1ZWUjZTV1V2VVRJNFptbHJVMkpTTDBaSVNVeGFRUXBCZDA1MlNYazBXVEZyUW5jdk9HZDFLMHBZUjJsWlJpdFNSVEJxYlRsc2VIazBaa0Z3VURKcmNqUnRWamhSVVhWT1FWaHRZVE5MV1VRdlpVSnJXa05UQ21ZeE56SmtaRWt5VmpOa2VDODNPRmxhVWtOSGNIZzFWRUkyWkhCWFJucFlVMDg0VHpkWmJEaHVhV2RXUzJSTmJtZElhMFo2ZERST1UxaFRNVzltV1dVS1VHWlRaQ3RFVURodVdHSk5aR3B3WlVaRFdtNWFkVEJXU0hrM2VXUlhXa1prTDNWRFdWSkxORTE1ZW5KWVkxTkNjRU5hWkdSdk5tbHRaMHBOUld0V1RncExXSEo0YTFoalpqbGxSVFprWTFwU1YzbGpRMEYzUlVGQllVNWFUVVpqZDBSbldVUldVakJRUVZGSUwwSkJVVVJCWjB0clRVRTRSMEV4VldSRmQwVkNDaTkzVVVaTlFVMUNRV1k0ZDBoUldVUldVakJQUWtKWlJVWkdXWE00WWs5R1VIbHlaMDFUTWxsM1JUTXpUMDlMYld0d1NsVk5RbFZIUVRGVlpFVlJVVThLVFVGNVEwTnRkREZaYlZaNVltMVdNRnBZVFhkRVVWbEtTMjlhU1doMlkwNUJVVVZNUWxGQlJHZG5SVUpCUTBwcVlYQlJlazE2ZURWMFZ6aHJhekE0VUFwVFEyVmpSV2hVWjFSVGRWWnBWMFUzVFhCemVIVTBXWGRrWkU5YWNYZFlRUzloVVVFeFRFZEhiRTl4YW5sSFRGUlFRakJhUmtwWlUxVllSMHAxY0U5dENrTlZXVU01Y2tGdVZrZG9SMGhPWVc4MmMyTkdOR3B0YkdzMWExUndhSE5vWmtWVU4xSk9iQzlTYjJ4Sk5IZFNMMjh6UlZKTVVGRm9NV001WWtsR2NVc0tWamc0TlRVd04yNUJRVmhHUm1rdlRHTnpjV3RxU2s5RGFraFJhMmhoTjJSTlVHNW5UVUpTYlZWMFN6SjZaWFZEU0RFd2FuQnlOazFpVERWdFNuQklUQXBvYVZKRFRXWnNaQzlQVmpWMFpUQlpXVEV2ZFd4c0wyZHZZa1ZxVEhFNVoxRlFRbnA1VUdkUEt6UmlURWw1UzNaWVQyWmtXVmhHWldaNFFURnZRM1ZhQ21aU1VpOVhNVTlOTVc5VFJ6RXpXVVEwYkdkd0swcG9kbTFqVlVoU1QwMVVRblk0VFV4Uk5saFJSM2RJTVZaSGRXNVRja3RVU1daSVYydFpXVU5JVFNzS09YZzRQUW90TFMwdExVVk9SQ0JEUlZKVVNVWkpRMEZVUlMwdExTMHRDZz09CiAgICBzZXJ2ZXI6IGh0dHBzOi8vMTAuMjMzLjAuMTo0NDMKICBuYW1lOiBrdWJlcm5ldGVzCmNvbnRleHRzOgotIGNvbnRleHQ6CiAgICBjbHVzdGVyOiBrdWJlcm5ldGVzCiAgICB1c2VyOiBrdWJlcm5ldGVzLWFkbWluCiAgbmFtZToga3ViZXJuZXRlcy1hZG1pbkBrdWJlcm5ldGVzCmN1cnJlbnQtY29udGV4dDoga3ViZXJuZXRlcy1hZG1pbkBrdWJlcm5ldGVzCmtpbmQ6IENvbmZpZwpwcmVmZXJlbmNlczoge30KdXNlcnM6Ci0gbmFtZToga3ViZXJuZXRlcy1hZG1pbgogIHVzZXI6CiAgICB0b2tlbjogZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklsaDFVbmxsYWpnNU5Fd3hURzFPTlc0MU9VYzVMV0UwUW5Jd00yTjBVWGR6U3pKclVHMXVVR0l6YmswaWZRLmV5SmhkV1FpT2xzaWFIUjBjSE02THk5cmRXSmxjbTVsZEdWekxtUmxabUYxYkhRdWMzWmpMbU5zZFhOMFpYSXViRzlqWVd3aVhTd2laWGh3SWpveE56RXhOelk0TURreUxDSnBZWFFpT2pFMk9EQXlNekl3T1RJc0ltbHpjeUk2SW1oMGRIQnpPaTh2YTNWaVpYSnVaWFJsY3k1a1pXWmhkV3gwTG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzSWl3aWEzVmlaWEp1WlhSbGN5NXBieUk2ZXlKdVlXMWxjM0JoWTJVaU9pSnJkV0psYzNCb1pYSmxMWE41YzNSbGJTSXNJbkJ2WkNJNmV5SnVZVzFsSWpvaWEzTXRZMjl1ZEhKdmJHeGxjaTF0WVc1aFoyVnlMV1prTkRRNVlqYzRZeTA0ZWpsb1pDSXNJblZwWkNJNklqQTJOekZoWm1FeUxUazRZV0l0TkRkaE1DMWhaVGN4TFRFeE5qYzFPREpqWWpVNU1TSjlMQ0p6WlhKMmFXTmxZV05qYjNWdWRDSTZleUp1WVcxbElqb2lhM1ZpWlhOd2FHVnlaU0lzSW5WcFpDSTZJamhsTm1Ga09XRTBMVEkxWXpNdE5ERXhOUzFoTnpoaUxUVmxNRE13T0dReU5EZzRPQ0o5TENKM1lYSnVZV1owWlhJaU9qRTJPREF5TXpVMk9UbDlMQ0p1WW1ZaU9qRTJPREF5TXpJd09USXNJbk4xWWlJNkluTjVjM1JsYlRwelpYSjJhV05sWVdOamIzVnVkRHByZFdKbGMzQm9aWEpsTFhONWMzUmxiVHByZFdKbGMzQm9aWEpsSW4wLmt1eUVlLWxqb203dUpBUlBJQ3BTbnhtR3ZCeWZ1QzZyZzhibHdlQVc1c0w2ZDE3WU1hS0wwVFFjVXg5TFZHRjlXZzNEY1lPQVBLOExlTWlkMm8yQW1XdkctMXl5dWctZzhlLVhiTW1LLWQ2RFNYeWhoakZjVG4zaDRGYWxVX0hscUdvZTIxY3VGZGNGTzNGQjJQTEc3VUNKUmZLZkF0b3BpcmdLNG5HblZJdmVOZjYwblZHUFAwZ0xQaHRzbFg1RjNYQV9KTE52bUtCeWlYS243Nno3YmxjQ0JOTDl0ME1LSnJTNF91OGQ0OEx5ZktXd2hSbWxnaEctX1V3aWh5Y3VOQzNqaDA0RS1qdFBUeHRGR1ZKVUF6TjhVSVBJQ1VZTUEwNXdaeDlzdTFCT2JtZlNMdUV2WnBzWXhBSmZmaDZvc2V0b01lMTRTOUl4dmJubW1sLUp6ZwogICAgdG9rZW5GaWxlOiAvdmFyL3J1bi9zZWNyZXRzL2t1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvdG9rZW4K
    kubernetesAPIEndpoint: https://10.233.0.1:443
    type: direct
  enable: true
  joinFederation: true
  provider: kubesphere
status:
  conditions:
  - lastTransitionTime: "2023-04-10T09:33:34Z"
    lastUpdateTime: "2023-04-10T09:33:34Z"
    message: Cluster has joined federation control plane successfully
    status: "True"
    type: Federated
  - lastTransitionTime: "2023-04-10T09:33:34Z"
    lastUpdateTime: "2023-04-10T09:33:34Z"
    message: Cluster is available now
    reason: Ready
    status: "True"
    type: Ready
  configz:
    alerting: true
    auditing: true
    authentication: true
    authorization: true
    devops: false
    edgeruntime: false
    events: false
    gateway: true
    gpu: true
    kubeedge: false
    kubernetes: true
    logging: false
    metering: true
    monitoring: true
    multicluster: true
    network: false
    network.ippool: false
    notification: true
    openpitrix: true
    openpitrix.appstore: false
    redis: false
    s3: false
    servicemesh: false
    sonarqube: false
    terminal: true
  kubeSphereVersion: v3.3.1
  kubernetesVersion: v1.23.10
  nodeCount: 3
  uid: 62f6b6f9-9c88-4c88-bf73-12f49f0b0004
